# Generated by Django 3.2.6 on 2021-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
